apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-techdocs
  description: An example techdocs of a Backstage application.
  annotations:
    github.com/project-slug: kenny-chow-my/techdocs-sample
    backstage.io/techdocs-ref: url:https://github.com/kenny-chow-my/techdocs-sample
spec:
  type: documentation
  owner: kenny-chow-my
  lifecycle: production